#!/bin/bash

case "$1" in
  --allow-write)
    ALLOW_WRITE=1
    shift
    ;;
  *)
    unset ALLOW_WRITE
    if which unionfs-fuse &>/dev/null; then
      /bin/true; # Unionfs FUSE is available
    else
      cat <<EOF

You need unionfs-fuse to use read-only mode. If you are careful, you
can use `--allow-write' to work in read-write mode instead.

EOF
      exit 1
    fi
    ;;
esac

if git in-repo; then
  echo "You're already in a git repo. Maybe try this?"
  echo "git $@"
  exit 1
fi

if [ -n "$ALLOW_WRITE" ]; then
  unset TMPDIR
else
  TMPDIR=`mktemp -d`
  unionfs-fuse "`pwd`"=RO $TMPDIR
  pushd $TMPDIR &>/dev/null
fi

for dir in */; do
  pushd $dir &>/dev/null
  if git in-repo; then
    echo "$dir"
    git "$@"
    echo "---------"
  fi
  popd &>/dev/null
done

if [ -n "$TMPDIR" ]; then
  popd &>/dev/null
  fusermount -uz $TMPDIR
  rmdir $TMPDIR
  grep $TMPDIR /proc/mounts
fi
