#!/bin/bash

if git in-repo; then
  true
else
  echo "You are not currently in a git repository"
  exit 1
fi

USERNAME=`git config github.user`
if [ -z "$USERNAME" ]; then
  cat <<EOF

You must set your github username in git:

    git config --global github.user USERNAME

EOF
  exit 1
fi

PREVIOUS_ORIGIN=`git config remote.origin.fetch`
if [ -n "$PREVIOUS_ORIGIN" ]; then
  case "$1" in
    -f|--force)
      shift
      ;;
    *)
      cat <<'EOF'

This repository already has an origin configured. If you want to
overwrite it, use `--force'.

EOF
      exit 1
      ;;
    esac
fi

# Finally, do it
if [ -n "$1" ]; then
  GITHUB_REPO_NAME="$1"
else
  # Default is name of pwd
  GITHUB_REPO_NAME="`basename \`pwd\``"
fi

ORIGIN_URL="git@github.com:${USERNAME}/${GITHUB_REPO_NAME}.git"

git config remote.origin.url "$ORIGIN_URL"
git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'

# Only set up remote if it isn't already set up.
MASTER_REMOTE=`git config branch.master.remote`
if [ -z "$MASTER_REMOTE" ]; then
  git config branch.master.remote origin
  git config branch.master.merge refs/heads/master
fi
